<package format="3">
  <name>display_video</name>
  <version>0.0.0</version>
  <description>Display ROS2 Image topic using OpenCV</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>ai_msgs</depend>
  <depend>message_filters</depend>
  <depend>libopencv-dev</depend> <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>